import { prisma } from "./prisma";
import { MatchData, SchoolData, PrizeData, RegistrationData } from "./types";

export const DEFAULT_SCHOOLS: SchoolData[] = [
  {
    id: "sch_1",
    name: "College of the Immaculate Conception (CIC)",
    slug: "cic-enugu",
    type: "MISSION",
    address: "Uwani, Enugu",
    lga: "Enugu South",
    state: "Enugu",
    motto: "Semper Fidelis",
    status: "CONFIRMED",
    matchesPlayed: 1,
    wins: 1,
    losses: 0,
    points: 248,
    seedRank: 1,
    teamMembers: [
      { id: "tm_1", schoolId: "sch_1", fullName: "Chukwuebuka Okonkwo", role: "CAPTAIN", classGrade: "SS3" },
      { id: "tm_2", schoolId: "sch_1", fullName: "Somtochukwu Eze", role: "SPEAKER", classGrade: "SS2" },
    ],
  },
  {
    id: "sch_2",
    name: "Federal Government College (FGC) Enugu",
    slug: "fgc-enugu",
    type: "FEDERAL",
    address: "Independence Layout, Enugu",
    lga: "Enugu North",
    state: "Enugu",
    motto: "Pro Unitate",
    status: "CONFIRMED",
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    points: 242,
    seedRank: 2,
    teamMembers: [
      { id: "tm_3", schoolId: "sch_2", fullName: "Ngozi Chimamanda Obi", role: "CAPTAIN", classGrade: "SS3" },
      { id: "tm_4", schoolId: "sch_2", fullName: "David Uchechukwu", role: "SPEAKER", classGrade: "SS3" },
    ],
  },
  {
    id: "sch_3",
    name: "Queen's School Enugu",
    slug: "queens-school-enugu",
    type: "PUBLIC",
    address: "Ogui Road, Enugu",
    lga: "Enugu North",
    state: "Enugu",
    motto: "Knowledge and Virtue",
    status: "CONFIRMED",
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    points: 236,
    seedRank: 3,
    teamMembers: [
      { id: "tm_5", schoolId: "sch_3", fullName: "Amarachi Blessing Nwankwo", role: "CAPTAIN", classGrade: "SS3" },
      { id: "tm_6", schoolId: "sch_3", fullName: "Chisom Precious Ugwu", role: "SPEAKER", classGrade: "SS3" },
    ],
  },
  {
    id: "sch_4",
    name: "St. Teresa's College (STC) Nsukka",
    slug: "st-teresas-college-nsukka",
    type: "MISSION",
    address: "University Road, Nsukka",
    lga: "Nsukka",
    state: "Enugu",
    motto: "Laborare est Orare",
    status: "CONFIRMED",
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    points: 230,
    seedRank: 4,
    teamMembers: [
      { id: "tm_7", schoolId: "sch_4", fullName: "Ifeanyi Emmanuel Ugwuoke", role: "CAPTAIN", classGrade: "SS3" },
      { id: "tm_8", schoolId: "sch_4", fullName: "Emeka Stanley Asogwa", role: "SPEAKER", classGrade: "SS2" },
    ],
  },
  {
    id: "sch_5",
    name: "Mea Mater Elizabeth High School",
    slug: "mea-mater-elizabeth-agbani",
    type: "PRIVATE",
    address: "Ojiagu, Agbani",
    lga: "Nkanu West",
    state: "Enugu",
    motto: "Excellence in Character and Learning",
    status: "CONFIRMED",
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    points: 228,
    seedRank: 5,
    teamMembers: [
      { id: "tm_9", schoolId: "sch_5", fullName: "Kamsiyochukwu Onyekachi", role: "CAPTAIN", classGrade: "SS3" },
      { id: "tm_10", schoolId: "sch_5", fullName: "Bryan Munachimso", role: "SPEAKER", classGrade: "SS2" },
    ],
  },
  {
    id: "sch_6",
    name: "Spring of Life International Schools",
    slug: "spring-of-life-enugu",
    type: "PRIVATE",
    address: "Abakpa Nike, Enugu",
    lga: "Enugu East",
    state: "Enugu",
    motto: "Illuminating the Future",
    status: "CONFIRMED",
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    points: 224,
    seedRank: 6,
    teamMembers: [
      { id: "tm_11", schoolId: "sch_6", fullName: "Precious Chidera Ozor", role: "CAPTAIN", classGrade: "SS3" },
      { id: "tm_12", schoolId: "sch_6", fullName: "Michael Tobenna Edeh", role: "SPEAKER", classGrade: "SS3" },
    ],
  },
  {
    id: "sch_7",
    name: "Holy Rosary College (HRC) Uwani",
    slug: "holy-rosary-college-enugu",
    type: "MISSION",
    address: "Zik Avenue, Uwani, Enugu",
    lga: "Enugu South",
    state: "Enugu",
    motto: "Servite Domino in Laetitia",
    status: "CONFIRMED",
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    points: 220,
    seedRank: 7,
    teamMembers: [
      { id: "tm_13", schoolId: "sch_7", fullName: "Chioma Stephanie Onoh", role: "CAPTAIN", classGrade: "SS3" },
      { id: "tm_14", schoolId: "sch_7", fullName: "Adaobi Jennifer Igwe", role: "SPEAKER", classGrade: "SS2" },
    ],
  },
  {
    id: "sch_8",
    name: "Command Day Secondary School Enugu",
    slug: "command-day-enugu",
    type: "FEDERAL",
    address: "82 Division Army Barracks, Abakpa",
    lga: "Enugu East",
    state: "Enugu",
    motto: "Discipline and Knowledge",
    status: "CONFIRMED",
    matchesPlayed: 1,
    wins: 0,
    losses: 1,
    points: 218,
    seedRank: 8,
    teamMembers: [
      { id: "tm_15", schoolId: "sch_8", fullName: "Victor Olusegun Babatunde", role: "CAPTAIN", classGrade: "SS3" },
      { id: "tm_16", schoolId: "sch_8", fullName: "Chinedu Paulinus Eze", role: "SPEAKER", classGrade: "SS2" },
    ],
  },
  {
    id: "sch_9",
    name: "Model High School Nsukka",
    slug: "model-high-school-nsukka",
    type: "PUBLIC",
    address: "Enugu Road, Nsukka",
    lga: "Nsukka",
    state: "Enugu",
    motto: "Strive for the Zenith",
    status: "CONFIRMED",
    matchesPlayed: 1,
    wins: 1,
    losses: 0,
    points: 214,
    seedRank: 9,
    teamMembers: [
      { id: "tm_17", schoolId: "sch_9", fullName: "Tobechukwu Franklin Ozioko", role: "CAPTAIN", classGrade: "SS3" },
      { id: "tm_18", schoolId: "sch_9", fullName: "Onyinyechi Sandra Eze", role: "SPEAKER", classGrade: "SS2" },
    ],
  },
  {
    id: "sch_10",
    name: "Air Force Comprehensive School Agbani",
    slug: "air-force-agbani",
    type: "FEDERAL",
    address: "Air Force Base, Agbani",
    lga: "Nkanu West",
    state: "Enugu",
    motto: "Per Ardua Ad Astra",
    status: "CONFIRMED",
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    points: 210,
    seedRank: 10,
    teamMembers: [
      { id: "tm_19", schoolId: "sch_10", fullName: "Oluwatobi Daniel Alabi", role: "CAPTAIN", classGrade: "SS3" },
      { id: "tm_20", schoolId: "sch_10", fullName: "Kosisochukwu Mbah", role: "SPEAKER", classGrade: "SS3" },
    ],
  },
  {
    id: "sch_11",
    name: "National Grammar School Nike",
    slug: "national-grammar-school-nike",
    type: "PUBLIC",
    address: "Nike Lake Road, Enugu",
    lga: "Enugu East",
    state: "Enugu",
    motto: "Truth and Diligence",
    status: "CONFIRMED",
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    points: 206,
    seedRank: 11,
    teamMembers: [
      { id: "tm_21", schoolId: "sch_11", fullName: "Chukwudi Samson Nnaji", role: "CAPTAIN", classGrade: "SS3" },
      { id: "tm_22", schoolId: "sch_11", fullName: "Chinaza Grace Ugwu", role: "SPEAKER", classGrade: "SS2" },
    ],
  },
  {
    id: "sch_12",
    name: "Urban Girls' Secondary School Enugu",
    slug: "urban-girls-enugu",
    type: "PUBLIC",
    address: "New Haven, Enugu",
    lga: "Enugu North",
    state: "Enugu",
    motto: "Character and Intellect",
    status: "CONFIRMED",
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    points: 202,
    seedRank: 12,
    teamMembers: [
      { id: "tm_23", schoolId: "sch_12", fullName: "Munachi Faith Okereke", role: "CAPTAIN", classGrade: "SS3" },
      { id: "tm_24", schoolId: "sch_12", fullName: "Perpetual Amarachi Ani", role: "SPEAKER", classGrade: "SS2" },
    ],
  },
  {
    id: "sch_13",
    name: "St. John Cross Seminary Nsukka",
    slug: "st-john-cross-nsukka",
    type: "MISSION",
    address: "Barracks Road, Nsukka",
    lga: "Nsukka",
    state: "Enugu",
    motto: "Virtus et Scientia",
    status: "CONFIRMED",
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    points: 198,
    seedRank: 13,
    teamMembers: [
      { id: "tm_25", schoolId: "sch_13", fullName: "Dominic Chidiebere Eze", role: "CAPTAIN", classGrade: "SS3" },
      { id: "tm_26", schoolId: "sch_13", fullName: "Augustine Kenechukwu Omeje", role: "SPEAKER", classGrade: "SS2" },
    ],
  },
  {
    id: "sch_14",
    name: "Enugu State University Demonstration Sec School",
    slug: "esut-demonstration-school",
    type: "PUBLIC",
    address: "Agbani Campus, Agbani",
    lga: "Nkanu West",
    state: "Enugu",
    motto: "Leading by Example",
    status: "CONFIRMED",
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    points: 194,
    seedRank: 14,
    teamMembers: [
      { id: "tm_27", schoolId: "sch_14", fullName: "Uchenna Jude Chukwu", role: "CAPTAIN", classGrade: "SS3" },
      { id: "tm_28", schoolId: "sch_14", fullName: "Chidera Cynthia Nnamani", role: "SPEAKER", classGrade: "SS2" },
    ],
  },
  {
    id: "sch_15",
    name: "Boys' High School Awgu",
    slug: "boys-high-school-awgu",
    type: "PUBLIC",
    address: "Old Oji Road, Awgu",
    lga: "Awgu",
    state: "Enugu",
    motto: "Courage and Honor",
    status: "CONFIRMED",
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    points: 190,
    seedRank: 15,
    teamMembers: [
      { id: "tm_29", schoolId: "sch_15", fullName: "Chibuike Collins Okoli", role: "CAPTAIN", classGrade: "SS3" },
      { id: "tm_30", schoolId: "sch_15", fullName: "Kingsley Ugochukwu", role: "SPEAKER", classGrade: "SS2" },
    ],
  },
  {
    id: "sch_16",
    name: "St. Paul's College Eke (Udi)",
    slug: "st-pauls-college-eke",
    type: "MISSION",
    address: "Eke Town, Udi",
    lga: "Udi",
    state: "Enugu",
    motto: "In Fide et Scientia",
    status: "CONFIRMED",
    matchesPlayed: 1,
    wins: 0,
    losses: 1,
    points: 188,
    seedRank: 16,
    teamMembers: [
      { id: "tm_31", schoolId: "sch_16", fullName: "Arinzechukwu Jude Ezeani", role: "CAPTAIN", classGrade: "SS3" },
      { id: "tm_32", schoolId: "sch_16", fullName: "Anthony Onyedikachi", role: "SPEAKER", classGrade: "SS2" },
    ],
  },
];

export const DEFAULT_PRIZES: PrizeData[] = [
  {
    id: "p1",
    tier: "CHAMPION",
    title: "ESSD 2026 GRAND CHAMPION",
    rewardHeadline: "Full International Scholarship + Cash Prize + Gold Championship Trophy",
    description: "Prestigious all-expense covered international higher education scholarship opportunity abroad, substantial cash award for the debate society, the official ESSD 2026 Championship Gold Trophy, gold medallions for each debater, and a fully equipped high-speed AI & digital resource lab grant for the school.",
    iconName: "Trophy",
    badgeColor: "gold",
    displayOrder: 1,
    isAnnounced: true,
  },
  {
    id: "p2",
    tier: "RUNNER_UP",
    title: "1ST RUNNER-UP (FINALIST)",
    rewardHeadline: "₦1,500,000 Cash Prize + Silver Plaque + Regional Leadership Fellowship",
    description: "Generous cash prize award, silver medals for all squad debaters, executive school plaque, and priority enrollment in the 2027 West Africa Youth Leadership & Public Policy Academy.",
    iconName: "Medal",
    badgeColor: "orange",
    displayOrder: 2,
    isAnnounced: true,
  },
  {
    id: "p3",
    tier: "THIRD_PLACE",
    title: "2ND RUNNER-UP (3RD PLACE)",
    rewardHeadline: "₦750,000 Cash Prize + Bronze Trophy + School Library Grant",
    description: "Bronze trophy, certificate of national academic distinction, cash reward for the school debate society, and institutional digital library subscriptions.",
    iconName: "Award",
    badgeColor: "cream",
    displayOrder: 3,
    isAnnounced: true,
  },
  {
    id: "p4",
    tier: "BEST_SPEAKER",
    title: "OVERALL BEST INDIVIDUAL SPEAKER",
    rewardHeadline: "International Youth Summit Delegate Seat + Laptops & Tech Suite",
    description: "Awarded to the debater with the highest cumulative individual speaker score across all rounds. Includes high-end laptop, AI research toolkit, and an all-expenses-paid delegate slot at the African Youth Debate Forum.",
    iconName: "Sparkles",
    badgeColor: "gold",
    displayOrder: 4,
    isAnnounced: true,
  },
  {
    id: "p5",
    tier: "SPECIAL",
    title: "BEST EMERGING SCHOOL AWARD",
    rewardHeadline: "Special Recognition + Debate Society Mentorship Grant",
    description: "Recognizing outstanding oratory excellence, research depth, and argumentation poise from a first-time championship participant school.",
    iconName: "Star",
    badgeColor: "orange",
    displayOrder: 5,
    isAnnounced: true,
  },
];

const MOTIONS = [
  "This House Would Replace Traditional Standardized Testing with AI-Driven Continuous Adaptive Evaluation in Nigerian Secondary Schools.",
  "This House Believes That Over-Reliance on Large Language Models Erodes Foundational Critical Thinking and Originality in Secondary Education.",
  "This House Would Make Foundational AI Literacy and Algorithmic Ethics a Compulsory Core Curriculum Subject Across All Nigerian Secondary Schools.",
  "This House Regrets the Monopolization of Educational AI Tools by Private EdTech Corporations.",
  "This House Believes That Human Teachers Possess Irreplaceable Emotional and Moral Mentorship That No Pedagogical Algorithm Can Replicate.",
  "This House Would Ban the Use of Generative AI for Homework and Continuous Assessment in Secondary Schools.",
  "This House Believes That AI-Driven Personalized Tutoring Will Widen the Educational Divide Between Urban and Rural Schools in Developing Nations.",
  "This House Would Prioritize Algorithmic Research over Traditional STEM Laboratory Funding in Developing Economies.",
  "This House Believes That Algorithmic Content Recommendations in Online Learning Platforms Foster Echo Chambers Detrimental to Intellectual Exploration.",
  "This House Would Hold EdTech Developers Legally Liable for Algorithmic Biases in Student Assessment Models.",
  "This House Believes That the Digitization of African Indigenous Knowledge Systems via Generative AI Risks Cultural Exploitation.",
  "This House Would Prohibit AI Tools from Assessing Subjective Student Competencies Such as Creativity, Empathy, and Leadership.",
  "This House Believes That Future Curricula Should Prioritize Philosophy, Ethics, and Logic Over Code Syntax in the Age of Autonomous Programming.",
  "This House Would Require All Secondary School Examinations to Be Administered Strictly Offline in Pen-and-Paper Formats.",
  "This House Believes That Human Intelligence, Not Artificial Intelligence, Must Remain the Ultimate Sovereign in Defining the Purpose and Soul of Education.",
];

const VENUE = "Main Auditorium, Enugu State Secretariat Complex, Independence Layout, Enugu";

export function generateDefaultMatches(): MatchData[] {
  const s = DEFAULT_SCHOOLS;

  return [
    // R16
    {
      id: "m_1",
      matchNumber: 1,
      round: "ROUND_OF_16",
      roundLabel: "Round of 16",
      roundOrder: 1,
      positionInRound: 1,
      schoolAId: s[0].id,
      schoolA: s[0],
      schoolBId: s[15].id,
      schoolB: s[15],
      winnerId: s[0].id,
      winner: s[0],
      scoreA: 84.5,
      scoreB: 72.0,
      motionTopic: MOTIONS[0],
      date: "16th Oct 2026",
      time: "09:00 AM",
      venueName: VENUE,
      judges: "Prof. Kenneth Nweke (Chief Adjudicator), Dr. Chinenye Igwe",
      status: "FINAL",
    },
    {
      id: "m_2",
      matchNumber: 2,
      round: "ROUND_OF_16",
      roundLabel: "Round of 16",
      roundOrder: 1,
      positionInRound: 2,
      schoolAId: s[7].id,
      schoolA: s[7],
      schoolBId: s[8].id,
      schoolB: s[8],
      winnerId: s[8].id,
      winner: s[8],
      scoreA: 79.0,
      scoreB: 81.5,
      motionTopic: MOTIONS[1],
      date: "16th Oct 2026",
      time: "09:45 AM",
      venueName: VENUE,
      judges: "Prof. Kenneth Nweke, Barr. Tochukwu Eze",
      status: "FINAL",
    },
    {
      id: "m_3",
      matchNumber: 3,
      round: "ROUND_OF_16",
      roundLabel: "Round of 16",
      roundOrder: 1,
      positionInRound: 3,
      schoolAId: s[3].id,
      schoolA: s[3],
      schoolBId: s[12].id,
      schoolB: s[12],
      winnerId: null,
      scoreA: 54.0,
      scoreB: 51.5,
      motionTopic: MOTIONS[2],
      date: "16th Oct 2026",
      time: "10:30 AM",
      venueName: VENUE,
      judges: "Dr. Chinenye Igwe, Barr. Tochukwu Eze",
      status: "LIVE",
    },
    {
      id: "m_4",
      matchNumber: 4,
      round: "ROUND_OF_16",
      roundLabel: "Round of 16",
      roundOrder: 1,
      positionInRound: 4,
      schoolAId: s[4].id,
      schoolA: s[4],
      schoolBId: s[11].id,
      schoolB: s[11],
      winnerId: null,
      scoreA: null,
      scoreB: null,
      motionTopic: MOTIONS[3],
      date: "16th Oct 2026",
      time: "11:15 AM",
      venueName: VENUE,
      judges: "Panel of Certified WSDC Adjudicators",
      status: "UPCOMING",
    },
    {
      id: "m_5",
      matchNumber: 5,
      round: "ROUND_OF_16",
      roundLabel: "Round of 16",
      roundOrder: 1,
      positionInRound: 5,
      schoolAId: s[1].id,
      schoolA: s[1],
      schoolBId: s[14].id,
      schoolB: s[14],
      winnerId: null,
      scoreA: null,
      scoreB: null,
      motionTopic: MOTIONS[4],
      date: "16th Oct 2026",
      time: "12:00 PM",
      venueName: VENUE,
      judges: "Panel of Certified WSDC Adjudicators",
      status: "UPCOMING",
    },
    {
      id: "m_6",
      matchNumber: 6,
      round: "ROUND_OF_16",
      roundLabel: "Round of 16",
      roundOrder: 1,
      positionInRound: 6,
      schoolAId: s[6].id,
      schoolA: s[6],
      schoolBId: s[9].id,
      schoolB: s[9],
      winnerId: null,
      scoreA: null,
      scoreB: null,
      motionTopic: MOTIONS[5],
      date: "16th Oct 2026",
      time: "12:45 PM",
      venueName: VENUE,
      judges: "Panel of Certified WSDC Adjudicators",
      status: "UPCOMING",
    },
    {
      id: "m_7",
      matchNumber: 7,
      round: "ROUND_OF_16",
      roundLabel: "Round of 16",
      roundOrder: 1,
      positionInRound: 7,
      schoolAId: s[2].id,
      schoolA: s[2],
      schoolBId: s[13].id,
      schoolB: s[13],
      winnerId: null,
      scoreA: null,
      scoreB: null,
      motionTopic: MOTIONS[6],
      date: "16th Oct 2026",
      time: "01:30 PM",
      venueName: VENUE,
      judges: "Panel of Certified WSDC Adjudicators",
      status: "UPCOMING",
    },
    {
      id: "m_8",
      matchNumber: 8,
      round: "ROUND_OF_16",
      roundLabel: "Round of 16",
      roundOrder: 1,
      positionInRound: 8,
      schoolAId: s[5].id,
      schoolA: s[5],
      schoolBId: s[10].id,
      schoolB: s[10],
      winnerId: null,
      scoreA: null,
      scoreB: null,
      motionTopic: MOTIONS[7],
      date: "16th Oct 2026",
      time: "02:15 PM",
      venueName: VENUE,
      judges: "Panel of Certified WSDC Adjudicators",
      status: "UPCOMING",
    },
    // Quarter-Finals
    {
      id: "m_9",
      matchNumber: 9,
      round: "QUARTER_FINALS",
      roundLabel: "Quarter-Finals",
      roundOrder: 2,
      positionInRound: 1,
      schoolAId: s[0].id,
      schoolA: s[0],
      schoolBId: s[8].id,
      schoolB: s[8],
      winnerId: null,
      scoreA: null,
      scoreB: null,
      motionTopic: MOTIONS[8],
      date: "16th Oct 2026",
      time: "03:30 PM",
      venueName: VENUE,
      judges: "Prof. Kenneth Nweke, Engr. Dr. Ifeoma Okafor",
      status: "UPCOMING",
    },
    {
      id: "m_10",
      matchNumber: 10,
      round: "QUARTER_FINALS",
      roundLabel: "Quarter-Finals",
      roundOrder: 2,
      positionInRound: 2,
      schoolAId: null,
      schoolBId: null,
      winnerId: null,
      scoreA: null,
      scoreB: null,
      motionTopic: MOTIONS[9],
      date: "16th Oct 2026",
      time: "04:15 PM",
      venueName: VENUE,
      judges: "Panel of Certified WSDC Adjudicators",
      status: "UPCOMING",
    },
    {
      id: "m_11",
      matchNumber: 11,
      round: "QUARTER_FINALS",
      roundLabel: "Quarter-Finals",
      roundOrder: 2,
      positionInRound: 3,
      schoolAId: null,
      schoolBId: null,
      winnerId: null,
      scoreA: null,
      scoreB: null,
      motionTopic: MOTIONS[10],
      date: "16th Oct 2026",
      time: "05:00 PM",
      venueName: VENUE,
      judges: "Panel of Certified WSDC Adjudicators",
      status: "UPCOMING",
    },
    {
      id: "m_12",
      matchNumber: 12,
      round: "QUARTER_FINALS",
      roundLabel: "Quarter-Finals",
      roundOrder: 2,
      positionInRound: 4,
      schoolAId: null,
      schoolBId: null,
      winnerId: null,
      scoreA: null,
      scoreB: null,
      motionTopic: MOTIONS[11],
      date: "16th Oct 2026",
      time: "05:45 PM",
      venueName: VENUE,
      judges: "Panel of Certified WSDC Adjudicators",
      status: "UPCOMING",
    },
    // Semi-Finals
    {
      id: "m_13",
      matchNumber: 13,
      round: "SEMI_FINALS",
      roundLabel: "Semi-Finals",
      roundOrder: 3,
      positionInRound: 1,
      schoolAId: null,
      schoolBId: null,
      winnerId: null,
      scoreA: null,
      scoreB: null,
      motionTopic: MOTIONS[12],
      date: "17th Oct 2026",
      time: "10:00 AM",
      venueName: VENUE,
      judges: "Grand Jury Panel",
      status: "UPCOMING",
    },
    {
      id: "m_14",
      matchNumber: 14,
      round: "SEMI_FINALS",
      roundLabel: "Semi-Finals",
      roundOrder: 3,
      positionInRound: 2,
      schoolAId: null,
      schoolBId: null,
      winnerId: null,
      scoreA: null,
      scoreB: null,
      motionTopic: MOTIONS[13],
      date: "17th Oct 2026",
      time: "11:30 AM",
      venueName: VENUE,
      judges: "Grand Jury Panel",
      status: "UPCOMING",
    },
    // Final
    {
      id: "m_15",
      matchNumber: 15,
      round: "FINAL",
      roundLabel: "Grand Final Championship",
      roundOrder: 4,
      positionInRound: 1,
      schoolAId: null,
      schoolBId: null,
      winnerId: null,
      scoreA: null,
      scoreB: null,
      motionTopic: MOTIONS[14],
      date: "17th Oct 2026",
      time: "02:30 PM",
      venueName: VENUE,
      judges: "State Keynote Panel: Ministry of Education, Tech Policy Council & WSDC Grand Adjudicators",
      status: "UPCOMING",
    },
  ];
}

// Resilient Data Getters that work seamlessly locally and on Vercel Serverless
export async function getSafeSchools(): Promise<SchoolData[]> {
  try {
    const schools = await prisma.school.findMany({
      include: { teamMembers: true },
      orderBy: [{ points: "desc" }, { name: "asc" }],
    });
    if (schools && schools.length > 0) return schools as any;
  } catch (err) {
    console.warn("Prisma query fallback to default schools:", err);
  }
  return DEFAULT_SCHOOLS;
}

export async function getSafeMatches(): Promise<MatchData[]> {
  try {
    const matches = await prisma.match.findMany({
      include: { schoolA: true, schoolB: true, winner: true },
      orderBy: { matchNumber: "asc" },
    });
    if (matches && matches.length > 0) return matches as any;
  } catch (err) {
    console.warn("Prisma query fallback to default matches:", err);
  }
  return generateDefaultMatches();
}

export async function getSafePrizes(): Promise<PrizeData[]> {
  try {
    const prizes = await prisma.prize.findMany({
      orderBy: { displayOrder: "asc" },
    });
    if (prizes && prizes.length > 0) return prizes as any;
  } catch (err) {
    console.warn("Prisma query fallback to default prizes:", err);
  }
  return DEFAULT_PRIZES;
}

export async function getSafeRegistrations(): Promise<RegistrationData[]> {
  try {
    const registrations = await prisma.registration.findMany({
      orderBy: { createdAt: "desc" },
    });
    return registrations as any;
  } catch (err) {
    console.warn("Prisma query fallback for registrations:", err);
    return [];
  }
}
